### ISSUE TITLE
Incorrect limit switch holder step files

### ISSUE THREAD

**Issue by alw1746** [culturalheritagedigital/Cindymill#1]
I think the STEP files for XY and Z axis limit switch holders refer to spindle mounts. See attached pics. The STL files are fine.
![Incorrect_limitswitch_XY](https://user-images.githubusercontent.com/1145579/201887034-2430d541-0012-40a6-8277-fcde414a16a1.jpg)
![Incorrect_limitswitch_Z](https://user-images.githubusercontent.com/1145579/201887108-eccb4d1d-e0a9-4bb8-b6d1-2ee8f9f484ce.jpg)

**Comment by culturalheritagedigital** [comment]
Hi, the elements depicted in your images are actually inductive proximity switches. Best regards

**Comment by alw1746** [comment]
Ah right, had no idea they looked like that. Thanks.
